### ISSUE TITLE
Do typos from reviews

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#125]

**Comment by apmcleod** [comment]
The file "reviews.txt" in overleaf contains up-to date status on reviewer comments, plus some comments and discussion (from me) that aren't listed here. The main points remaining are:

- Evaluate tasks 1,3,4 by degradation type. #127 
- Why 5 second excerpts? (Most are longer due to ties, but still, 2 reviewers mentioned this).
- Some soft assertions like "to our judgement" in the new measure_errors.py explanation.
- Decide about mentioning generation in conclusion or not.
- A few things to add to future work (#32, voice/track degradations, other tasks).

And one point from me:
We may want to change the title (currently "Symbolic music correction using the MIDI degradation toolkit"). I think it is still possible to do. I'm worried that people will skip the paper if they don't work on symbolic data, and now that we have the Degrader class, and the focus is strongly on AMT data aug/noise, we don't want to miss that audience.

Some options:
"Music Correction using The MIDI Degradation Toolkit"
"Error Correction using The MIDI Degradation Toolkit"
"Musical Error Correction using The MIDI Degradation Toolkit"

**Comment by JamesOwers** [comment]
Things remaining:
- Add figure explaining pianoroll and command format and slim down text
- Add reference "Investigating the Perceptual Validity of Evaluation Metrics for Automatic Piano Music Transcription. Transactions of the International Society for Music Information Retrieval"
- Add columns to confusion matrix figure with results by class for tasks 3 and 4
- Add introduction to ACME dataset
