### ISSUE TITLE
There may be an issue with the pitch_shift distribution arg

### ISSUE THREAD

**Issue by JamesOwers** [JamesOwers/midi_degradation_toolkit#155]
to reproduce:
```
pitches = [64, 64, 65, 67, 67, 65, 64, 62, 60, 60, 62, 64, 64, 62, 62]
bpm = 120
beat_dur = 60/bpm * 1000
durations = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.5, .5, 2]
durations = [beats*beat_dur for beats in durations]
onsets = [sum(durations[:ii]) for ii in range(len(durations))]
excerpt = pd.DataFrame(
    {
        "onset": onsets,
        "pitch": pitches,
        "dur": durations,
    }
)
excerpt["track"] = 0
pitch_shift(
    excerpt,
    min_pitch=60,
    max_pitch=68,
    distribution=[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    seed=42,
    tries=1,
)
```
causes `ValueError: probabilities contain NaN`

The process is causing divide by zero issues. No time to check just now.

**Comment by apmcleod** [comment]
The sampled note is only allowed to pitch shift up or down 5 semitones based on `distribution`.

However, for the first sampled note (`pitch = 64`), both of these are invalid due to `min_pitch` and `max_pitch`. Adding a check for np.sum == 0 fixes this issue and returns `None` with a tries warning. Raising tries allows the degradation to then complete successfully. I will fix and add a test for this case.
