### ISSUE TITLE
Decide what to do with "invalid" MIDI

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#20]
e.g., dur==0, overlapping notes, etc. Assert and fail? Or warn?

**Comment by JamesOwers** [comment]
We need to clean out overlapping notes of the same pitch from excerpts. This is because conversion to commands now becomes a non-invertible function (it screws it all up!). This is because we have to assume that the first occurring note_off command for a given pitch is the note_off for the oldest pitch coming on (or, at least *an* assumption must be made, there's no way of us telling which way round it was). For example:

```
df = pd.DataFrame({
    'onset': [0, 40, 80, 120],
    'track' : 0,
    'pitch': [60, 60, 60, 60],
    'dur': [80, 20, 40, 60]
})

df
Out[102]: 
   onset  track  pitch  dur
0      0      0     60   80
1     40      0     60   20
2     80      0     60   40
3    120      0     60   60

cmd_str = df_to_command_str(df)

cmd_str
Out[104]: 'o60 t40 o60 t20 f60 t20 f60 o60 t40 f60 o60 t60 f60'

command_str_to_df(cmd_str)
Out[105]: 
   onset  track  pitch  dur
0      0      0     60   60
1     40      0     60   40
2     80      0     60   40
3    120      0     60   60
```

**Comment by apmcleod** [comment]
Also related to that problem: #46 and #8

**Comment by apmcleod** [comment]
Maybe the simplest (but not best or most elegant) way to solve all of these issues is:
1. Remove the track column (for now at least)
2. Skip invalid MIDI (including those which now have overlapping notes because we ignore the tracks)
3. Add a check to degradations.post_process for overlapping notes which will instead return None.

**Comment by apmcleod** [comment]
I'm going to call this fixed now, since our set of midi all loads, and we skip some empty files and fix overlaps.

We can reopen if any weird midi files show up.
