### ISSUE TITLE
Don't suppress all warnings in train and eval

### ISSUE THREAD

**Issue by apmcleod** [JamesOwers/midi_degradation_toolkit#88]
In particular, warning the user about --seq_len being too small is very important.

I tried to filter that warning with 'once', but:
1. Python only filters the first occurrence of *each exact warning message*, even if multiple messages match the same filter's regex.
2. For some reason, it's not working anyways, probably because the warnings are being printed by the dataloader workers?

These seem to be the only warnings printed during train or test (when everything goes smoothly), so I think notifying the user is important, and removing the full ignore filter will allow through other warnings from actual errors.

**Comment by JamesOwers** [comment]
Ultimately I think switching to the package [logging](https://docs.python.org/3.7/library/logging.html) is probably a better plan for future. Given that we are not expecting many to use our code directly to create models, is this one case of seq_len important?

I would err on the side of 'warnings all off' unless debug mode is on, just so that logging is at a minimum for the casual user.

**Comment by apmcleod** [comment]
I dunno really. If we don't expect users to create models, they won't see the --seq_len warning anyways. That only shows up when training/testing models (and really is important in those cases I'd say, since we're giving them bad data).

**Comment by JamesOwers** [comment]
Since this is not actually affecting the creation of ACME v1.0, I'm going to kick to the next milestone. We should discuss via skype then, I think it'll be quicker, and record the resolution here.
